apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-nginx-index
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Welcome to Argo CD!</title>
      </head>
      <body>
        <h1>This is sivasakthi</h1>
        <p>If you see this page, your GitOps pipeline works!</p>
      </body>
    </html>
