apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd # Must match the namespace where Argo CD is installed
spec:
  project: default # The Argo CD project the application belongs to
  source:
    repoURL: https://github.com/your-org/your-repo.git # URL of the Git repository
    targetRevision: HEAD # Branch, tag, or commit to sync from (e.g., main, v1.0.0)
    path: guestbook # Path within the repository where manifests are located
    # Optional: For Helm charts
    # chart: my-helm-chart
    # helm:
    #   valueFiles:
    #     - values.yaml
  destination:
    server: https://kubernetes.default.svc # Target cluster API server URL
    namespace: my-app-namespace # Namespace in the target cluster for deployment
  syncPolicy:
    automated:
      prune: true # Automatically delete resources not in Git
      selfHeal: true # Automatically sync if live state deviates from Git
    syncOptions:
      - CreateNamespace=true # Create the destination namespace if it doesn't exist
      - ApplyOutOfSyncOnly=true # Only apply changes to out-of-sync resources